------------------------------------------
-- CZ3003 GROUP SSP1 
-- PineapplePoptarts
-- SOFTWARE LAB 3 
-- DATABASE SCHEMA: CREATION OF TABLES 
------------------------------------------

/* Create accountTbl for Call Operator's Login Details */
-- ins_date refers to when is the account being registered/requested
-- upd_date refers to when was the change of either password or username
-- sessionkey i.e. is assumed to be generated by the system when account was created
CREATE TABLE accountTbl (
username varchar(25) NOT NULL,
password varchar(25) NOT NULL,	
sessionkey varchar(25) NOT NULL, 
ins_date datetime DEFAULT GETDATE(), 
upd_date datetime DEFAULT GETDATE(),

CONSTRAINT PK_account PRIMARY KEY (username) 
)


/* Create incidentTbl for recording all initial report of incidents */
-- ins_name and ipd_name refers to ther username in accountTbl 
-- status == 1 means resolved and status == 0 means unresolved
CREATE TABLE incidentTbl (
recordID int NOT NULL,
name varchar(100) NOT NULL,
contact int NOT NULL,
location varchar(1000) NOT NULL, 
assistanceType varchar(1000) NOT NULL, 
description varchar(200),
status bit DEFAULT 0, 
ins_date datetime DEFAULT GETDATE(),
ins_name varchar(25),
upd_date datetime DEFAULT GETDATE(),
upd_name varchar(25),

CONSTRAINT PK_incident PRIMARY KEY (recordID),
CONSTRAINT FK_name1 FOREIGN KEY (ins_name) REFERENCES accountTbl(username),
CONSTRAINT FK_name2 FOREIGN KEY (upd_name) REFERENCES accountTbl(username)
)


/* Create updIncidentTbl for recording all updates regarding the incident */

CREATE TABLE updIncidentTbl(
recordID int NOT NULL,
updates varchar(max), 
assistanceType varchar(1000),
reportedBy varchar(50) NOT NULL,
status bit DEFAULT 0, 
ins_date datetime DEFAULT GETDATE(),
ins_name varchar(25)

CONSTRAINT PK_updIncident PRIMARY KEY (recordID, ins_date),
CONSTRAINT FL_updIncident FOREIGN KEY (recordID) REFERENCES incidentTbl(recordID)
)

