//"Client Side"

var io = require('socket.io-client');
var socket = io.connect("http://localhost:4000/", {
    reconnection: true
});

var socketServerTwo = require('socket.io');
var ioServerTwo =  socket.listener(5000); // Listen to messages on port 5000

// Listen to DB for a report submission

ioServerTwo.on('receiveincidentreport', (socket,reportdata)=>{

// serverTwo will emit 'incidentreport' event to port 4000 when it has received 'receiveincidentreport' event from DB at port 5000
socket.emit('incidentreport',reportdata); 

});


/*serverTwo needs to listen for a message from the client (i.e Report submission) 
and send the data back to serverOne

e.g 

socket.on('reportSubmission' , )

socket.on('connect', ()=>{

    console.log('connected to localhost:4000');


    // Listens to ClientEvent generated by serverOne
    socket.on('clientEvent' , data =>{

        console.log('message from the server:', data);
        socket.emit('serverEvent', "thanks server! for sending '" + data + "'" )

    });

});
*/


